version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smartdine-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smartdine
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - smartdine-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: smartdine-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - smartdine-network

  # SmartDine API Server
  api:
    build:
      context: .
      target: dev
    container_name: smartdine-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/smartdine?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_key_here_change_in_production
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_key_here_change_in_production
      RAZORPAY_KEY_ID: your_razorpay_key_id
      RAZORPAY_KEY_SECRET: your_razorpay_key_secret
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - smartdine-network

  # React Client (will be added later)
  # client:
  #   build:
  #     context: ./client
  #   container_name: smartdine-client
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_URL: http://localhost:5000/api
  #   depends_on:
  #     - api
  #   networks:
  #     - smartdine-network

volumes:
  mongodb_data:
  redis_data:

networks:
  smartdine-network:
    driver: bridge